[project]
name = "github-copilot-openai-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.14",
    "async-lru>=2.0.5",
    "fastapi>=0.115.11",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "uvicorn>=0.34.0",
]
